# Generated by Django 3.2.6 on 2023-05-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='credit',
            field=models.ManyToManyField(to='movies.Credits'),
        ),
        migrations.AddField(
            model_name='movie',
            name='detail',
            field=models.ManyToManyField(to='movies.Detail'),
        ),
        migrations.AddField(
            model_name='movie',
            name='recommend',
            field=models.ManyToManyField(to='movies.Recommend'),
        ),
    ]
